version: 2

models:
  # ===========================================================================
  # Staging Models
  # ===========================================================================
  - name: stg_ohlcv
    description: "Cleaned OHLCV data from raw parquet files"
    columns:
      - name: symbol
        description: "Cryptocurrency symbol (BTC, ETH, etc.)"
        tests:
          - not_null
      - name: trade_date
        description: "Trading date"
        tests:
          - not_null
      - name: close_price
        description: "Closing price"
        tests:
          - not_null
          - positive_value

  - name: stg_trades
    description: "Cleaned trade logs from CSV files"
    columns:
      - name: account_name
        description: "Trading account identifier"
        tests:
          - not_null
      - name: trade_action
        description: "Trade action (BUY or SELL)"
        tests:
          - not_null
          - accepted_values:
              values: ['BUY', 'SELL']

  - name: stg_backtest_results
    description: "Cleaned backtest results from JSON files"
    columns:
      - name: symbol
        tests:
          - not_null
      - name: strategy
        tests:
          - not_null

  # ===========================================================================
  # Intermediate Models
  # ===========================================================================
  - name: int_daily_features
    description: "Technical indicators calculated from OHLCV data"
    columns:
      - name: symbol
        tests:
          - not_null
      - name: trade_date
        tests:
          - not_null
      - name: rsi_14
        description: "14-day RSI (0-100)"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100

  - name: int_trade_pnl
    description: "Matched trades with P&L calculation"
    columns:
      - name: position_status
        tests:
          - accepted_values:
              values: ['OPEN', 'CLOSED']

  # ===========================================================================
  # Mart Models
  # ===========================================================================
  - name: mart_trading_performance
    description: "Aggregated trading performance by account and symbol"
    columns:
      - name: account_name
        tests:
          - not_null
      - name: win_rate
        description: "Win rate (0-1)"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 1

  - name: mart_daily_metrics
    description: "Daily metrics combining features and trading activity"
    tests:
      - unique:
          column_name: "symbol || '-' || trade_date"

  - name: mart_backtest_summary
    description: "Backtest results summary by strategy"
